In [20]:
import numpy as np
import random
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import LSTM, Dense

In [21]:
print("Enter size of binary strings")
size = int(input())
num = 500000

Enter size of binary strings
15


In [22]:
X = np.zeros((num, size, 2), dtype=int)
Y = np.zeros((num, size), dtype=int)

In [23]:
for i in range(num):
    for j in range(size):
        X[i][j][0]=random.randint(0, 1)
        X[i][j][1]=random.randint(0, 1)
        Y[i][j] = X[i][j][0]^X[i][j][1]

In [24]:
print(X)
print(Y)

[[[1 1]
  [1 0]
  [1 0]
  ...
  [1 1]
  [1 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 1]
  ...
  [1 1]
  [0 0]
  [0 1]]

 [[0 0]
  [1 1]
  [1 0]
  ...
  [0 0]
  [1 1]
  [0 0]]

 ...

 [[1 1]
  [0 1]
  [1 0]
  ...
  [1 1]
  [0 1]
  [1 1]]

 [[1 0]
  [0 0]
  [0 0]
  ...
  [1 1]
  [0 1]
  [1 0]]

 [[1 1]
  [1 1]
  [0 1]
  ...
  [1 0]
  [1 1]
  [0 1]]]
[[0 1 1 ... 0 1 0]
 [0 0 1 ... 0 0 1]
 [0 0 1 ... 0 0 0]
 ...
 [0 1 1 ... 0 1 0]
 [1 0 0 ... 0 1 1]
 [0 0 1 ... 1 0 1]]


In [25]:
model = Sequential()

In [26]:
model.add(LSTM(size, input_shape=(size,2)))

In [27]:
model.add(Dense(size, activation="sigmoid"))

In [28]:
model.summary()
model.compile("adam", loss="binary_crossentropy", metrics=["accuracy"])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 15)                1080      
_________________________________________________________________
dense_2 (Dense)              (None, 15)                240       
Total params: 1,320
Trainable params: 1,320
Non-trainable params: 0
_________________________________________________________________


In [29]:
x_train,x_test,y_train,y_test=train_test_split(X,Y)

In [30]:
model.fit(x_train, y_train, epochs=3, batch_size=32)

Epoch 1/3
375000/375000 [==============================] - 78s 207us/step - loss: 0.4079 - acc: 0.7924
Epoch 2/3
375000/375000 [==============================] - 76s 202us/step - loss: 0.1536 - acc: 0.9384
Epoch 3/3
375000/375000 [==============================] - 71s 189us/step - loss: 0.0681 - acc: 0.9779


In [31]:
loss, accuracy= model.evaluate(x_test,y_test)

125000/125000 [==============================] - 4s 35us/step


In [32]:
accuracy*100


98.879521068573